-- AlterTable
ALTER TABLE `menu_items` 
    ADD COLUMN IF NOT EXISTS `description` VARCHAR(500) NULL,
    ADD COLUMN IF NOT EXISTS `image` VARCHAR(500) NULL,
    ADD COLUMN IF NOT EXISTS `is_mega` BOOLEAN NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS `mega_columns` INTEGER NULL DEFAULT 4,
    ADD COLUMN IF NOT EXISTS `css_class` VARCHAR(255) NULL;
